<?php

declare(strict_types=1);

/**
 * @file
 * Provides a thumbs_up_event entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function thumbs_up_theme(): array {
  return [
    'thumbs_up_event' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for thumbs_up_event templates.
 *
 * Default template: thumbs-up-event.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the thumbs_up_event information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_thumbs_up_event(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function thumbs_up_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish thumbs_up_events.
      $storage = \Drupal::entityTypeManager()->getStorage('thumbs_up_event');
      $thumbs_up_event_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($thumbs_up_event_ids) as $thumbs_up_event) {
        $thumbs_up_event->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize thumbs_up_events.
      $storage = \Drupal::entityTypeManager()->getStorage('thumbs_up_event');
      $thumbs_up_event_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($thumbs_up_event_ids) as $thumbs_up_event) {
        $thumbs_up_event->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function thumbs_up_user_predelete(UserInterface $account): void {
  // Delete thumbs_up_events that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('thumbs_up_event');
  $thumbs_up_event_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($thumbs_up_event_ids)
  );
}
