# Schema for the configuration files of the vienna_2025_thumbs_up module.
vienna_2025_frontdesk.settings:
  type: config_object
  label: 'vienna_2025_frontdesk settings'
  mapping:
    config:
      type: text
      label: 'Config (in Json format)'
